# Generated by Django 2.0.5 on 2020-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0015_auto_20200710_1253'),
        ('account', '0003_auto_20200706_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_ads',
            field=models.ManyToManyField(related_name='user_ads', to='adverts.Advert'),
        ),
    ]
