# Generated by Django 2.0.5 on 2020-07-10 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0014_auto_20200709_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
